version: '3.8'

services:
  # 1. Reverse Proxy (Nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  # 2. Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # 3. Backend Core (FastAPI via uv)
  backend:
    build:
      image: xihxxn/todowith-backend:latest
      container_name: todowith-backend
    volumes:
      - .:/app
    command: uv run uvicorn app.app:app --host 0.0.0.0 --port 8000 --workers 4
    
    env_file:
      - ./.env.secret
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # 4. Database (PostgreSQL)
  postgres:
    image: pgvector/pgvector:pg15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # 5. In-Memory DB / Message Broker (Redis)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  pg_data:
  redis_data:


networks:
  app-network:
    driver: bridge
